name: Clippy

on:
  push:
    branches:
      - v2
      - v1
  pull_request:
    branches:
      - v2
      - v1

jobs:
  clippy:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt update && sudo apt install libwebkit2gtk-4.1-dev
        if: matrix.platform == 'ubuntu-latest'
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets --all-features -- -D warnings
